//-----------------------------------------------------------------------------
// File: ComponentHeader
//
// Desc: 컴포넌트의 *.cpp에서 사용하기 편하도록 헤더 파일 모음 (*.h에서 사용 금지)
//-----------------------------------------------------------------------------

#pragma once
#include "StandardLibrary.h"
#include "DXHeader.h"
#include "Functions.h"
#include "Raycast.h"
#include "Frustum.h"
#include "CallBack.h"
#include "Time.h"
#include "Global.h"
#include "PrebuiltObjects.h"
#include "ComponentManager.h"
#include "SceneManager.h"
#include "MeshManager.h"
#include "TextureManager.h"
#include "FontManager.h"
#include "Transform.h"
#include "RectTransform.h"
#include "Renderer.h"
#include "MeshRenderer.h"
#include "VerticeRenderer.h"
#include "TextRenderer.h"
#include "SpriteRenderer.h"
#include "Animator.h"
#include "MouseFunction.h"
#include "Collider.h"
#include "BoxCollider.h"
#include "SphereCollider.h"
#include "Collider2D.h"
#include "BoxCollider2D.h"
#include "SphereCollider2D.h"
#include "Camera.h"
#include "CallBack.h"
#include "Button.h"
#include "CheckBox.h"
#include "ContentBox.h"
#include "ViewBox.h"
#include "Scroll.h"
#include "ScrollBar.h"